### ISSUE TITLE
Error: The `main` key in your `package.json` file is required; it must specify the entry point of your Worker.

### ISSUE THREAD

**Issue by billymaulana** [cloudflare/worker-template#37]
when wrangler publish i get this error.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/13347455/163214883-2fc2d871-65fe-4750-80fb-70add5fdbedb.png">

wrangler.toml
<img width="870" alt="image" src="https://user-images.githubusercontent.com/13347455/163215170-6247f5dc-16d0-4292-9d17-844c5391ed85.png">
 
 my workers files:
 
<img width="317" alt="image" src="https://user-images.githubusercontent.com/13347455/163215303-4a1864a4-a63e-4ad5-95e8-24a91e42e703.png">

whats the problem ? missing configuration ?

**Comment by Missarceneaux33** [comment]
> when wrangler publish i get this error.
> 
> <img alt="image" width="870" src="https://user-images.githubusercontent.com/13347455/163214883-2fc2d871-65fe-4750-80fb-70add5fdbedb.png">
> 
> wrangler.toml <img alt="image" width="870" src="https://user-images.githubusercontent.com/13347455/163215170-6247f5dc-16d0-4292-9d17-844c5391ed85.png">
> 
> my workers files:
> 
> <img alt="image" width="317" src="https://user-images.githubusercontent.com/13347455/163215303-4a1864a4-a63e-4ad5-95e8-24a91e42e703.png">
> 
> whats the problem ? missing configuration ?

yes
